version: "3"
services:
  book_catalog:
    build: ./book_catalog
    container_name: book_catalog_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db_215076784_sit722_part33_user:yu1lqg8MWJM5nemg92tb93USysqkSLxh@dpg-crjs4plds78s73edlen0-a.oregon-postgres.render.com/db_215076784_sit722_part33?sslmode=require

  inventory_management:
    build: ./inventory_management
    container_name: inventory_management_service
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db_215076784_sit722_part33_user:yu1lqg8MWJM5nemg92tb93USysqkSLxh@dpg-crjs4plds78s73edlen0-a.oregon-postgres.render.com/db_215076784_sit722_part33?sslmode=require

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: db_215076784_sit722_part33_user
      POSTGRES_PASSWORD: yu1lqg8MWJM5nemg92tb93USysqkSLxh
      POSTGRES_DB: book_catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
